name: CI

on:
  push:
    branches: [ main, BK01, BK02, FN01 ]
  pull_request:

jobs:
  django-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Django system checks
        run: |
          python manage.py check

      - name: Validate migrations are up-to-date
        run: |
          python manage.py makemigrations --check --dry-run


